name: Create Repositories from Template

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'GIVE THE NAME'
        required: true

jobs:
  create_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository from template
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          TEMPLATE_OWNER: ${{ github.repository_owner }}
          TEMPLATE_REPO: ${{ github.event.repository.name }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$TEMPLATE_OWNER/$TEMPLATE_REPO/generate \
            -d "{\"owner\":\"$TEMPLATE_OWNER\",\"name\":\"${REPO_NAME// /}\",\"include_all_branches\":false,\"private\":false}"